export const iconNames = {
    eye: "eye",
    eyeOff: "eyeOff",
    chevronDown: "chevronDown",
    chevronsUpDown: "chevronsUpDown",
    chevronUp: "chevronUp",
    gripVertical: "gripVertical",
    chevronsLeft: "chevronsLeft",
    chevronLeft: "chevronLeft",
    chevronsRight: "chevronsRight",
    chevronRight: "chevronRight",
    download: "download",
    close: "close",
    filter: "filter",
    settings: "settings",
    coffee: "coffee",
    users: "users",
    dashboard: "dashboard",
    receipt: "receipt",
    circleGauge: "circleGauge",
    edit: "edit",
    trash: "trash",
    check: "check",
    wallet: "wallet",
} as const;

export type IconName = (typeof iconNames)[keyof typeof iconNames];
